# Generated by Django 5.1.6 on 2025-02-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pessoa_endereco_alter_pessoa_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='rua',
            new_name='logradouro',
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
