# Generated by Django 5.1.6 on 2025-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rua_endereco_logradouro_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
