# Generated by Django 5.1.6 on 2025-02-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pessoa_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='api.endereco'),
        ),
    ]
