# Generated by Django 5.1.6 on 2025-03-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_min_age_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='update',
            new_name='updated',
        ),
    ]
