# Generated by Django 5.1.6 on 2025-03-04 22:22

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contato_created_by_contato_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.CharField(blank=True, help_text='Categorias separadas por vírgula (ex: Música, Jovens, Culto)', max_length=100, null=True, verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveBigIntegerField(blank=True, help_text='Número máximo de participantes permitidos', null=True, verbose_name='Capacidade máxima'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Data limite para os participantes se inscreverem', null=True, verbose_name='Data limite para inscrição'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Indica se o evento requer pagamento para participação', verbose_name='Requer pagamento'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True),
        ),
    ]
