# Generated by Django 5.1.6 on 2025-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_event_options_event_categories_event_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.RemoveField(
            model_name='contato',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='created',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='created',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Data de fim do Evento.', verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_age',
            field=models.DateField(help_text='Idade mínima para inscrição no evento.', null=True, verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Data de ínicio do evento', verbose_name='Data de Início'),
        ),
    ]
